apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix-cluster-cleanup
  title: Radix Cluster Cleanup
  description: "Keeps the Playground cluster tidy, stops and deletes 'unused' applications, as a scheduled service"
  annotations:
    github.com/project-slug: equinor/radix-cluster-cleanup
spec:
  type: service
  lifecycle: production
  owner: team-radix
  system: Radix
