name: radix-cluster-cleanup-pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: pull-request-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t radix-cluster-cleanup:${REF##*/} .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install GolangCI Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: Install dependencies
        run: go mod download
        working-directory: radix-cluster-cleanup
      - name: golangci-lint
        working-directory: radix-cluster-cleanup
        run: golangci-lint run --timeout=30m --max-same-issues=0 --out-format=github-actions
